function language = load_language(lang, paradigm_tasks)
    switch lang
        case 'eng'
            end_message = ...
                ['\nPlease do not turn away from the screen and try not to blink during the tasks\n\n',...
                 'only in the small breaks, when task description appeares.\n\n',...
                 '\nTell us if you are ready!'];

            middle_message = ...
                ['\nWe are going to display the upcoming task,\n\n',...
                 'after that a fixation cross will appear for 4 seconds.\n\n',...
                 'You have to execute the appropriate task during this time.\n\n',...
                 'Repeat the tasks for each second!\n\n'];
             
            constrict = '- Constrict the sponge with your ';
            imagine_constriction = '- Imagine that you are constricting the sponge with your ';
            
            tread = '- Tread the sponge with your ';
            imagine_treading = '- Imagine that you are treading the sponge with your ';
             
            language.task_eye = ...
                ['You have to execute 2 different tasks during recording: \n\n',...
                 '- watch the monitor with opened eyes                  \n\n',...
                 '- close your eye and wait for the end signal.         \n\n',...
                 end_message];
             
            switch paradigm_tasks
                case 'a' % left hand, right hand, left foot, right foot
                    language.task_12 = ...
                        ['You have to execute 4 different tasks during recording:\n\n',...
                         constrict, 'RIGHT hand!                         \n\n',...
                         constrict, 'LEFT hand!                          \n\n',...
                         imagine_constriction, 'RIGHT hand! \n\n',...
                         imagine_constriction, 'LEFT hand!  \n\n',...
                         middle_message, end_message];
              
                    language.task_34 = ...
                        ['You have to execute 4 different tasks during recording:\n\n',...
                         tread, 'RIGHT foot!                         \n\n',...
                         tread, 'LEFT foot!                          \n\n',...
                         imagine_treading, 'RIGHT foot!     \n\n',...
                         imagine_treading, 'LEFT foot!      \n\n',...
                         middle_message, end_message];

                    language.task_mixed_1234 = ...
                        ['You have to execute 4 different tasks during recording:\n\n',...
                         imagine_constriction, 'RIGHT hand! \n\n',...
                         imagine_constriction, 'LEFT hand!  \n\n',...
                         imagine_treading, 'RIGHT foot!     \n\n',...
                         imagine_treading, 'LEFT foot!      \n\n',...
                         middle_message, end_message];
                     
                    language.task_1_m_text = 'Constrict RIGHT hand'; % CHECK in send trigger!!!
                    language.task_2_m_text = 'Constrict LEFT hand';
                    language.task_1_mi_text = 'Imagine RIGHT hand constriction';
                    language.task_2_mi_text = 'Imagine LEFT hand constriction';
                    
                    language.task_3_m_text = 'Tread with RIGHT foot';
                    language.task_4_m_text = 'Tread with LEFT foot';
                    language.task_3_mi_text = 'Imagine RIGHT foot treading';
                    language.task_4_mi_text = 'Imagine LEFT foot treading';
                     
                case 'b' % left hand, right hand, booth hands, booth foots
                    language.task_12 = ...
                        ['You have to execute 4 different tasks during recording:\n\n',...
                         constrict, 'RIGHT hand!                         \n\n',...
                         constrict, 'LEFT hand!                          \n\n',...
                         imagine_constriction, 'RIGHT hand! \n\n',...
                         imagine_constriction, 'LEFT hand!  \n\n',...
                         middle_message, end_message];
              
                    language.task_34 = ...
                        ['You have to execute 4 different tasks during recording:\n\n',...
                         constrict, 'BOTH hands!                         \n\n',...
                         tread, 'BOTH foots!                              \n\n',...
                         imagine_constriction, 'BOTH hands! \n\n',...
                         imagine_treading, 'BOTH foots!      \n\n',...
                         middle_message, end_message];

                    language.task_mixed_1234 = ...
                        ['You have to execute 4 different tasks during recording:\n\n',...
                         imagine_constriction, 'RIGHT hand! \n\n',...
                         imagine_constriction, 'LEFT hand!  \n\n',...
                         imagine_constriction, 'BOTH hands! \n\n',...
                         imagine_treading, 'BOTH foots!      \n\n',...
                         middle_message, end_message];
                     
                    language.task_1_m_text = 'Constrict RIGHT hand'; % RIGHT!!!!
                    language.task_2_m_text = 'Constrict LEFT hand';
                    language.task_1_mi_text = 'Imagine RIGHT hand constriction';
                    language.task_2_mi_text = 'Imagine LEFT hand constriction';
                    
                    language.task_3_m_text = 'Constrict Both HANDS';
                    language.task_4_m_text = 'Tread with Both FOOTS';
                    language.task_3_mi_text = 'Imagine Both HANDS constriction';
                    language.task_4_mi_text = 'Imagine Both FOOTS treading';
                    
                case 'c' % left hand, right hand, booth foots, calm
                    language.task_12 = ...
                        ['You have to execute 4 different tasks during recording:\n\n',...
                         constrict, 'RIGHT hand!                         \n\n',...
                         constrict, 'LEFT hand!                          \n\n',...
                         imagine_constriction, 'RIGHT hand! \n\n',...
                         imagine_constriction, 'LEFT hand!  \n\n',...
                         middle_message, end_message];
              
                    language.task_34 = ...
                        ['You have to execute 3 different tasks during recording:\n\n',...
                         '- Sit calmly with open eyes!                         \n\n',...
                         tread, 'BOTH foots!                              \n\n',...
                         imagine_treading, 'BOTH foots!      \n\n',...
                         middle_message, end_message];

                    language.task_mixed_1234 = ...
                        ['You have to execute 4 different tasks during recording:\n\n',...
                         imagine_constriction, 'RIGHT hand! \n\n',...
                         imagine_constriction, 'LEFT hand!  \n\n',...
                         imagine_treading, 'BOTH foots!      \n\n',...
                         '- Sit calmly with open eyes!                         \n\n',...
                         middle_message, end_message];
                     
                    language.task_1_m_text = 'Constrict RIGHT hand'; % RIGHT!!!!
                    language.task_2_m_text = 'Constrict LEFT hand';
                    language.task_1_mi_text = 'Imagine RIGHT hand constriction';
                    language.task_2_mi_text = 'Imagine LEFT hand constriction';
                    
                    language.task_3_m_text = 'CALM sit with open eyes';
                    language.task_4_m_text = 'Tread with Both FOOTS';
                    language.task_3_mi_text = 'CALM sit with open eyes';
                    language.task_4_mi_text = 'Imagine Both FOOTS treading';
                    
                case 'd' % active, active, rest, rest,
                    constrict = '- Constrict the sponges repeatedly! \n\n';
                    imagine_constriction = '- Imagine sponge constriction repeatedly! \n\n';
                    calm_sit = '- Sit calmly with open eyes! \n\n';
                    
                    language.task_12 = ...
                        ['You have to execute 3 different tasks during recording:\n\n',...
                         constrict,...
                         imagine_constriction,...
                         calm_sit, ...
                         middle_message, end_message];
              
                    language.task_34 = ...
                        ['You have to execute 3 different tasks during recording:\n\n',...
                         constrict,...
                         imagine_constriction,...
                         calm_sit, ...
                         middle_message, end_message];
                    
                    language.task_mixed_1234 = ...
                        ['You have to execute 2 different tasks during recording:\n\n',...
                         imagine_constriction,...
                         calm_sit,...
                         middle_message, end_message];
                     
                    calm_sit = 'Calm sit with open eyes';
                    active = 'ACTIVE sponge constriction';
                    imagined_active = 'Imagined constriction';
                    
                    language.task_1_m_text = active;
                    language.task_2_m_text = calm_sit;
                    language.task_1_mi_text = imagined_active;
                    language.task_2_mi_text = calm_sit;
                    
                    language.task_3_m_text = active;
                    language.task_4_m_text = calm_sit;
                    language.task_3_mi_text = imagined_active;
                    language.task_4_mi_text = calm_sit;
                    
                otherwise
                    error('Wrong input parameter in paradigm_tasks!')
            end

            language.thanks = 'Thank you! We are done.';
            language.welcome = 'Hi!';
            
            language.open_eye = 'Watch the fixation cross for 1 minute';
            language.closed_eye = 'Close your eyes for 1 minute';

        case 'hun'
            end_message = ...
                ['\nNe fordulj el a képernyõ elõl és kérlek a kereszt\n\n',...
                 'jelenléte alatt lehetõleg ne, vagy minél kevesebbet pislogj!\n\n',...
                 '\nSzólj ha készen állsz!'];

            middle_message = ...
                ['\nA feladatokat szövegesen jelenítjük meg\n\n',...
                 'ezt követõen egy kereszt jelenik meg 4 másodpercig,\n\n',...
                 'ez idõ alatt kell végrehajtanod a feladatot!\n\n',...
                 'A feladatokat másodpercenként ismételd!\n\n'];
             
            constrict = '- Ökölbe szorítani ';
            imagine_constriction = '- Elképzelni, hogy ökölbe szorítod ';
            
            tread = '- Megtaposni ';
            imagine_treading = '- Elképzelni, hogy megtaposod ';

            language.task_eye = ...
                ['A felvétel során 2 különbözõ feladatot kell majd végrehajtanod:\n\n',...
                 '- nyitott szemmel, illetve                          \n\n',...
                 '- csukott szemmel ülni.                             \n\n',...
                 end_message];
             
            switch paradigm_tasks
                case 'a'
                    language.task_12 = ...
                        ['A felvétel során 4 különbözõ feladatot kell majd végrehajtanod:\n\n',...
                         constrict, 'a jobb kezed!                      \n\n',...
                         constrict, 'a bal kezed!                       \n\n',...
                         imagine_constriction, 'a jobb kezed!     \n\n',...
                         imagine_constriction, 'a bal kezed!      \n\n',...
                         middle_message, end_message];

                    language.task_34 = ...
                        ['A felvétel során 4 különbözõ feladatot kell majd végrehajtanod:\n\n',...
                         tread, 'a jobb lábad alatti szivacsot                  \n\n',...
                         tread, 'a bal lábad alatti szivacsot                   \n\n',...
                         imagine_treading, 'a jobb lábad alatti szivacsot \n\n',...
                         imagine_treading, 'a bal lábad alatti szivacsot  \n\n',...
                         middle_message, end_message];

                    language.task_mixed_1234 = ...
                        ['A felvétel során 4 különbözõ feladatot kell majd végrehajtanod:\n\n',...
                         imagine_constriction, 'a jobb kezed!     \n\n',...
                         imagine_constriction, 'a bal kezed!      \n\n',...
                         imagine_treading, 'a jobb lábad alatti szivacsot \n\n',...
                         imagine_treading, 'a bal lábad alatti szivacsot  \n\n',...
                         middle_message, end_message];
                     
                    language.task_1_m_text = 'JOBB ököl szorítás';
                    language.task_2_m_text = 'BAL ököl szorítás';
                    language.task_1_mi_text = 'Elképzelt JOBB ököl szorítás';
                    language.task_2_mi_text = 'Elképzelt BAL ököl szorítás';
                    
                    language.task_3_m_text = 'JOBB láb taposás';
                    language.task_4_m_text = 'BAL láb taposás';
                    language.task_3_mi_text = 'Elképzelt JOBB láb taposás';
                    language.task_4_mi_text = 'Elképzelt BAL láb taposás';
                     
                case 'b'
                    language.task_12 = ...
                        ['A felvétel során 4 különbözõ feladatot kell majd végrehajtanod:\n\n',...
                         constrict, 'a jobb kezed!                        \n\n',...
                         constrict, 'a bal kezed!                         \n\n',...
                         imagine_constriction, 'a jobb kezed!     \n\n',...
                         imagine_constriction, 'a bal kezed!      \n\n',...
                         middle_message, end_message];

                    language.task_34 = ...
                        ['A felvétel során 4 különbözõ feladatot kell majd végrehajtanod:\n\n',...
                         constrict, 'mindkét kezed!                                           \n\n',...
                         tread, 'a lábaid alatt lévõ szivacsokat!                           \n\n',...
                         imagine_constriction, 'mindkét kezed!                   \n\n',...
                         imagine_treading, 'a lábaid alatt lévõ szivacsokat!\n\n',...
                         middle_message, end_message];

                    language.task_mixed_1234 = ...
                        ['A felvétel során 4 különbözõ feladatot kell majd végrehajtanod:\n\n',...
                         imagine_constriction, 'a jobb kezed!    \n\n',...
                         imagine_constriction, 'a bal kezed!      \n\n',...
                         imagine_constriction, 'mindkét kezed! \n\n',...
                         imagine_treading, 'a lábaid alatt lévõ szivacsokat!\n\n',...
                         middle_message, end_message];
                     
                    language.task_1_m_text = 'JOBB ököl szorítás';
                    language.task_2_m_text = 'BAL ököl szorítás';
                    language.task_1_mi_text = 'Elképzelt JOBB ököl szorítás';
                    language.task_2_mi_text = 'Elképzelt BAL ököl szorítás';
                    
                    language.task_3_m_text = 'Minkét ÖKÖL szorítása';
                    language.task_4_m_text = 'Mindkét LÁB taposása';
                    language.task_3_mi_text = 'Elképzelt Mindkét ÖKÖL szorítása';
                    language.task_4_mi_text = 'Elképzelt Mindkét LÁB taposása';
                    
                case 'c' % left hand, right hand, booth foots, calm
                    language.task_12 = ...
                        ['A felvétel során 4 különbözõ feladatot kell majd végrehajtanod:\n\n',...
                         constrict, 'a jobb kezed!                        \n\n',...
                         constrict, 'a bal kezed!                         \n\n',...
                         imagine_constriction, 'a jobb kezed!     \n\n',...
                         imagine_constriction, 'a bal kezed!      \n\n',...
                         middle_message, end_message];
              
                    language.task_34 = ...
                        ['A felvétel során 3 különbözõ feladatot kell majd végrehajtanod:\n\n',...
                         '- Nyitott szemmel nyugodtan ülni!                         \n\n',...
                         tread, 'a lábaid alatt lévõ szivacsokat!                           \n\n',...
                         imagine_treading, 'a lábaid alatt lévõ szivacsokat!\n\n',...
                         middle_message, end_message];

                    language.task_mixed_1234 = ...
                        ['A felvétel során 4 különbözõ feladatot kell majd végrehajtanod:\n\n',...
                         imagine_constriction, 'a jobb kezed!     \n\n',...
                         imagine_constriction, 'a bal kezed!      \n\n',...
                         imagine_treading, 'a lábaid alatt lévõ szivacsokat!\n\n',...
                         '- Nyitott szemmel nyugodtan ülni!                         \n\n',...
                         middle_message, end_message];
                     
                    language.task_1_m_text = 'JOBB ököl szorítás';
                    language.task_2_m_text = 'BAL ököl szorítás';
                    language.task_1_mi_text = 'Elképzelt JOBB ököl szorítás';
                    language.task_2_mi_text = 'Elképzelt BAL ököl szorítás';
                    
                    language.task_3_m_text = 'Ülj nyugodtan nyitott szemmel';
                    language.task_4_m_text = 'Mindkét LÁB taposása';
                    language.task_3_mi_text = 'Ülj nyugodtan nyitott szemmel';
                    language.task_4_mi_text = 'Elképzelt Mindkét LÁB taposása';
                    
                case 'd' % active, active, rest, rest,
                    constrict = '- Aktívan kéz és láb billentést végezni. \n\n';
                    imagine_constriction = '- Elképzelni, a kéz és láb billentéseket. \n\n';
                    calm_sit = '- Nyitott szemmel nyugodtan ülni! \n\n';
                    
                    language.task_12 = ...
                        ['A felvétel során 3 különbözõ feladatot kell majd végrehajtanod:\n\n',...
                         constrict,...
                         imagine_constriction,...
                         calm_sit,...
                         middle_message, end_message];
              
                    language.task_34 = ...
                        ['A felvétel során 3 különbözõ feladatot kell majd végrehajtanod:\n\n',...
                         constrict,...
                         imagine_constriction,...
                         calm_sit,...
                         middle_message, end_message];
                    
                    language.task_mixed_1234 = ...
                        ['A felvétel során 2 különbözõ feladatot kell majd végrehajtanod:\n\n',...
                         imagine_constriction,...
                         calm_sit,...
                         middle_message, end_message];
                    
                    calm_sit = 'NYUGODT ülés nyitott szemmel';
                    active = 'AKTÍV kéz és láb billentés';
                    imagined_active = 'ELKÉPZELT kéz és láb billentés';
                    
                    language.task_1_m_text = active;
                    language.task_2_m_text = calm_sit;
                    language.task_1_mi_text = imagined_active;
                    language.task_2_mi_text = calm_sit;
                    
                    language.task_3_m_text = active;
                    language.task_4_m_text = calm_sit;
                    language.task_3_mi_text = imagined_active;
                    language.task_4_mi_text = calm_sit;
                    
                otherwise
                    error('Wrong input parameter in paradigm_tasks!')
            end

            language.thanks = 'Köszönjük, végeztünk!';
            language.welcome = 'Üdv!';
            
            language.open_eye = 'Nézd a keresztet 1 percig';
            language.closed_eye = 'Csukd be a szemed 1 percre';
            
        otherwise
            error([lang, ' language is not defined.'])
    end
