function language = load_language(lang)
    if ~exist('lang','var')
        lang = 'eng';
    end
    switch lang
        case 'eng'
            end_message = ...
                ['Please do not turn away from the screen and try not to blink during the tasks\n\n',...
                 'only in the small breaks, when task description appeares.\n\n',...
                 'Tell us if you are ready!'];

            middle_message = ...
                ['We are going to display the upcoming task,\n\n',...
                 'after that a fixation cross will appear for 4 seconds.  \n\n',...
                 'You have to execute the appropriate task during this time\n\n'];
             
            language.task_eye = ...
                ['You have to execute 2 different tasks during recording: \n\n',...
                 '- watch the monitor with opened eyes                  \n\n',...
                 '- close your eye and wait for the end signal.         \n\n',...
                 end_message];

            language.task_hand = ...
                ['You have to execute 4 different tasks during recording:\n\n',...
                 '- Constrict the foam with your RIGHT hand!                         \n\n',...
                 '- Constrict the foam with your LEFT hand!                          \n\n',...
                 '- Imagine that you are constricting the foam with your RIGHT hand! \n\n',...
                 '- Imagine that you are constricting the foam with your LEFT hand!  \n\n',...
                 middle_message, end_message];

            language.task_foot = ...
                ['You have to execute 4 different tasks during recording:\n\n',...
                 '- Constrict the foam with your RIGHT foot!                         \n\n',...
                 '- Constrict the foam with your LEFT foot!                          \n\n',...
                 '- Imagine that you are constricting the foam with your RIGHT foot! \n\n',...
                 '- Imagine that you are constricting the foam with your LEFT foot!  \n\n',...
                 middle_message, end_message];

            language.task_hand_foot = ...
                ['You have to execute 4 different tasks during recording:\n\n',...
                 '- Imagine that you are constricting the foam with your RIGHT hand! \n\n',...
                 '- Imagine that you are constricting the foam with your LEFT hand!  \n\n',...
                 '- Imagine that you are constricting the foam with your RIGHT foot! \n\n',...
                 '- Imagine that you are constricting the foam with your LEFT foot!  \n\n',...
                 middle_message, end_message];

            language.thanks = 'Thank you! We are done.';

            language.welcome = 'Hi!';
            
            language.right_hand_m_text = 'Constrict RIGHT hand\n\n';
            language.left_hand_m_text = 'Constrict LEFT hand\n\n';
            language.right_hand_mi_text = 'Imagine RIGHT hand constriction\n\n';
            language.left_hand_mi_text = 'Imagine LEFT hand constriction\n\n';
            
            language.right_foot_m_text = 'Tread with RIGHT foot\n\n';
            language.left_foot_m_text = 'Tread with LEFT foot\n\n';
            language.right_foot_mi_text = 'Imagine RIGHT foot treading\n\n';
            language.left_foot_mi_text = 'Imagine LEFT foot treading\n\n';


        case 'hun'
            end_message = ...
                ['Ne fordulj el a képernyõ elõl és kérlek igyekezz\n\n',...
                 'csak a kereszt jelenléte alatt pislogni.\n\n',...
                 'Szólj ha készen állsz!'];

            middle_message = ...
                ['A feladatokat szövegesen jelenítjük meg\n\n',...
                 'ezt követõen egy kereszt jelenik meg 4 másodpercig,  \n\n',...
                 'ez idõ alatt kell végrehajtanod a feladatot! \n\n'];

            language.task_eye = ...
                ['A felvétel során 2 különbözõ feladatot kell majd végrehajtanod:\n\n',...
                 '- nyitott szemmel, illetve                          \n\n',...
                 '- csukott szemmel ülni.                             \n\n',...
                 end_message];

            language.task_hand = ...
                ['A felvétel során 4 különbözõ feladatot kell majd végrehajtanod:\n\n',...
                 '- Szorítsd ökölbe a jobb kezed!                      \n\n',...
                 '- Szorítsd ökölbe a bal kezed!                       \n\n',...
                 '- Képzeld el, hogy ökölbe szorítod a jobb kezed!     \n\n',...
                 '- Képzeld el, hogy ökölbe szorítod a bal kezed!      \n\n',...
                 middle_message, end_message];

            language.task_foot = ...
                ['A felvétel során 4 különbözõ feladatot kell majd végrehajtanod:\n\n',...
                 '- Megtaposni a jobb lábad alatti labdát                  \n\n',...
                 '- Megtaposni a bal lábad alatti labdát                   \n\n',...
                 '- Képzeld el, hogy megtaposod a jobb lábad alatti labdát \n\n',...
                 '- Képzeld el, hogy megtaposod a bal lábad alatti labdát  \n\n',...
                 middle_message, end_message];

            language.task_hand_foot = ...
                ['A felvétel során 4 különbözõ feladatot kell majd végrehajtanod:\n\n',...
                 '- Képzeld el, hogy ökölbe szorítod a jobb kezed!         \n\n',...
                 '- Képzeld el, hogy ökölbe szorítod a bal kezed!          \n\n',...
                 '- Képzeld el, hogy megtaposod a jobb lábad alatti labdát \n\n',...
                 '- Képzeld el, hogy megtaposod a bal lábad alatti labdát  \n\n',...
                 middle_message, end_message];

            language.thanks = 'Köszönjük, végeztünk!';

            language.welcome = 'Üdv!';
            
            language.right_hand_m_text = 'Jobb ököl szorítás\n\n';
            language.left_hand_m_text = 'Bal ököl szorítás\n\n';
            language.right_hand_mi_text = 'Elképzelt jobb ököl szorítás\n\n';
            language.left_hand_mi_text = 'Elképzelt bal ököl szorítás\n\n';
            
            language.right_foot_m_text = 'Jobb láb taposás\n\n';
            language.left_foot_m_text = 'Bal láb taposás\n\n';
            language.right_foot_mi_text = 'Elképzelt jobb láb taposás\n\n';
            language.left_foot_mi_text = 'Elképzelt bal láb taposás\n\n';
            
        otherwise
            error([lang, ' language is not defined.'])
    end
