function answer = savedialogbox
d = dialog('Position',[300 300 250 250],'Name','Save');
elem = [];

y = 200;
dy = 18;
elem(1) = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 y 210 40],...
               'String','File name will be genereated like:');
y = y - dy;           
elem(2) = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 y 210 40],...
               'String','ExperimentNumber_SubjectID.eeg');
y = y - 2 * dy;           
elem(3) = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 y 210 40],...
               'String','ExperimentNumber:');

elem(4) = uicontrol('Parent', d, ...
                    'Style', 'edit', ...
                    'Position', [20 y 210 20], ...
                    'String', 'rec');
                
y = y - 3 * dy;           
elem(5) = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 y 210 40],...
               'String','SubjectID:');

elem(6) = uicontrol('Parent', d, ...
                    'Style', 'edit', ...
                    'Position', [20 y 210 20], ...
                    'String', '01');


elem(7) = uicontrol('Parent',d,...
               'Position',[85 20 70 25],...
               'String','OK',...
               'Callback',@close_dialog);

uiwait(d);
           
    function close_dialog(btn, event)
        answer(1) = get(elem(4),{'String'});
        answer(2) = get(elem(6),{'String'});
        delete(gcbf);
    end
           
% align(elem, 'Left', 'None');
end  
